### ISSUE TITLE
Support for current version of "extensible"?

### ISSUE THREAD

**Issue by peti** [fumieval/call#3]
We would like to update to `extensible-0.2.6` in NixOS, but unfortunately that update will break `call-0.1.2`. See http://hydra.cryp.to/build/525902/nixlog/1/raw for a complete build log. Would it be possible to port the `call` package to the latest version?

Also, I noticed that the Cabal file prevents build with current versions of OpenGL: http://packdeps.haskellers.com/feed?needle=exact%3Acall. I believe the package builds just fine with the new OpenGL, though, and there should be no problem lifting that restriction from the Cabal file.

**Comment by fumieval** [comment]
Sure, but it needs fine tuning on several platforms, with new OpenGL. I will upload an updated version as soon as I confirm that it works.

**Comment by Fuuzetsu** [comment]
Any news?

**Comment by fumieval** [comment]
Released 0.1.3 for now.

I've not yet succeeded to get on with Mac; I'm replacing OpenGL with Edward's gl library to clarify.
